### ISSUE TITLE
Re-enable Travis

### ISSUE THREAD

**Issue by mion00** [coorasse/Airesis#130]
I see you use Codeship to check the build, but is it possible to re-enable Travis? Because at the moment I can't see any build details regarding the project on Codeship.

**Comment by coorasse** [comment]
We moved to codeship from Travis few months ago because Travis was not able to run all the tests. After few months trying we moved to codeship.
Codeship doesn't support builds for pull request intra-repository.
Please feel free to run the build on travis and see if it works on the new Travis infrastructure. I'm open for changes. :)

**Comment by mion00** [comment]
I managed to run the test in a Docker container.. I am currently finishing it up!

**Comment by coorasse** [comment]
Well done!

**Comment by mion00** [comment]
OK, I think that #134 is ready, if you would like to enable Travis again..
